// This file will be auto-generated by:
//   npx supabase gen types typescript --project-id <id> > src/types/database.ts
// Placeholder until Supabase project is provisioned.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
